// src/types/models.ts

export type ObjectId = string;

export interface RewardFileStructure {
  pointTomanRate: number;
  items: RewardEntryInput[];
}

export enum RewardType {
  Gem = 'Gem',
  Gold = 'Gold',
  Chest = 'Chest',
  HeroCardAndSkin = 'HeroCardAndSkin',
  DailyGem = 'DailyGem',
  HeroAbilityCard = 'HeroAbilityCard',
  NewHero = 'NewHero',
  Skin = 'Skin',
  HeroCard = 'HeroCard',
  BattleGoldBoost = 'BattleGoldBoost',
  NormalChestBoost = 'NormalChestBoost',
  CrownChestBoost = 'CrownChestBoost',
  CrownRushBoost = 'CrownRushBoost',
  QuestPointBoost = 'QuestPointBoost',
  AdPlus = 'AdPlus',
  HeroFragment = 'HeroFragment',
  HeroTicket = 'HeroTicket',
  SkinFragment = 'SkinFragment',
  ChestKey = 'ChestKey',
  ChestsDynamite = 'ChestsDynamite',
  AllCards = 'AllCards',
  SelfBoost = 'SelfBoost',
  BattlePass = 'BattlePass',
  EventLeagueLeaderboardUnlock = 'EventLeagueLeaderboardUnlock',
  EventLeagueExpand = 'EventLeagueExpand',
}

export enum chestType {
  None = -1,
  Tutorial1,
  Tutorial2,
  Free,
  Wooden,
  Silver,
  Crown,
  Giant,
  Magical,
  SuperMagical,
  Rent,
  LeaderBoard,
  Tournament,
  Tournament2,
  ClanWarBronze,
  ClanWarSilver,
  ClanWarGold,
  Fortune,
  PiggyBankV2,
}

export interface RewardEntryInput {
  id: string; // Now required
  requiredPoint?: number;
  reward: any;
  additionalDetail?: any;
}

export const HERO_REWARD_TYPES = new Set([
  'HeroCard',
  'HeroAbilityCard',
  'Skin',
  'NewHero',
]);

export const ALL_SKINS: Set<string> = new Set([
  'changiz_goldenweapon',
  'shapoor_oneeye',
  'shaboon_harleydavidson',
  'esi_kaftarbaz',
  'taghi_colonel',
  'samurai_fullmetalarmored',
  'boxer_punky',
  'robert_joker',
  'ghabrkan_moldy',
  'sharare_blonde',
  'kambiz_kolahbadi',
  'ghobad_sammi',
  'zombie_bony',
  'changiz_leonthepro',
  'sahara_gladiator',
  'shapoor_terminator',
  'davood_kz',
  'doctor_surgeon',
  'shaboon_wrestling',
  'nanjoon_godmother',
  'taghi_black',
  'shahin_purple',
  'sasan_balmaske',
  'ghabrkan_dracula',
  'samurai_chinesehat',
  'kambiz_santaclaus',
  'heshmat_amoonorooz',
  'davood_capone',
  'heshmat_blackjacket',
  'kambiz_beach',
  'dozd_loki',
  'davood_bond',
  'shahin_madmax',
  'jasem_samjackson',
  'parastar_horror',
  'zinat_victorian',
  'nanjoon_christmas',
  'afsoon_modernfighter',
  'bijan_victorian',
  'parastar_supernurse',
  'ghobad_hajifirooz',
  'esi_rapper',
  'mahpeykar_wizard',
  'gambler_saintpatrick',
  'mechanic_steampunk',
  'pinhead_thor',
  'swat_robocap',
  'comiser_jeremybrett',
  'sahara_cleopatra',
  'doctor_adventure',
  'jasem_worldcup22',
  'chenli_whitemask',
  'sharare_robot',
  'robert_sevensin',
  'pirate_tropical',
  'sasan_saswick',
  'ghobad_ghobadwhite',
  'boxer_aztec',
  'afsoon_cute',
  'kambiz_lolo',
  'samurai_yakuza',
  'ghabrkan_nightking',
  'gypsy_senua',
  'gypsy_senua_v2',
  'taghi_lukyluke',
  'taghi_lukylukev2',
  'swat_blizzardfang',
  'heshmat_godofwar_v1',
  'heshmat_godofwar_v2',
  'babajan_diver_v1',
  'babajan_diver_v2',
  'changiz_rambov1',
  'changiz_rambov2',
  'shapoor_hawaii_v1',
  'shapoor_hawaii_v2',
  'balsamic_bababarghi_v1',
  'balsamic_bababarghi_v2',
  'zombie_ghostrider',
  'dozd_grunch_v1',
  'dozd_grunch_v2',
  'chenli_ling',
  'yavar_fisher_v1',
  'yavar_fisher_v2',
  'ammekaty_witch_v1',
  'ammekaty_witch_v2',
  'nanjoon_catwoman_v2',
]);

export const EXCLUSIVE_SKINS: Set<string> = new Set([
  'gypsy_senua',
  'taghi_lukyluke',
  'heshmat_godofwar_v1',
  'changiz_rambov1',
  'shapoor_hawaii_v1',
  'balsamic_bababarghi_v1',
  'babajan_diver_v1',
  'dozd_grunch_v1',
  'esi_hairdresser_v1',
  'esi_hairdresser_v2',
  'nanjoon_catwoman_v1',
  'ammekaty_witch_v1',
  'ammekaty_witch_v2',
  'pirate_halloween_v1',
  'pirate_halloween_v2',
  'davood_lizard_v1',
  'mahpeykar_darkqueen_v1',
]);
