export type SkinDefinition = {
  heroId: number;
  skinId: string;
};

export const SKINS: SkinDefinition[] = [
  { heroId: 0, skinId: 'changiz_goldenweapon' },
  { heroId: 5, skinId: 'shapoor_oneeye' },
  { heroId: 2, skinId: 'shaboon_harleydavidson' },
  { heroId: 11, skinId: 'esi_kaftarbaz' },
  { heroId: 3, skinId: 'taghi_colonel' },
  { heroId: 25, skinId: 'samurai_fullmetalarmored' },
  { heroId: 22, skinId: 'boxer_punky' },
  { heroId: 18, skinId: 'robert_joker' },
  { heroId: 15, skinId: 'ghabrkan_moldy' },
  { heroId: 16, skinId: 'sharare_blonde' },
  { heroId: 4, skinId: 'kambiz_kolahbadi' },
  { heroId: 9, skinId: 'ghobad_sammi' },
  { heroId: 20, skinId: 'zombie_bony' },
  { heroId: 0, skinId: 'changiz_leonthepro' },
  { heroId: 27, skinId: 'sahara_gladiator' },
  { heroId: 5, skinId: 'shapoor_terminator' },
  { heroId: 6, skinId: 'davood_kz' },
  { heroId: 8, skinId: 'doctor_surgeon' },
  { heroId: 2, skinId: 'shaboon_wrestling' },
  { heroId: 14, skinId: 'nanjoon_godmother' },
  { heroId: 3, skinId: 'taghi_black' },
  { heroId: 1, skinId: 'shahin_purple' },
  { heroId: 7, skinId: 'sasan_balmaske' },
  { heroId: 15, skinId: 'ghabrkan_dracula' },
  { heroId: 25, skinId: 'samurai_chinesehat' },
  { heroId: 4, skinId: 'kambiz_santaclaus' },
  { heroId: 10, skinId: 'heshmat_amoonorooz' },
  { heroId: 6, skinId: 'davood_capone' },
  { heroId: 10, skinId: 'heshmat_blackjacket' },
  { heroId: 4, skinId: 'kambiz_beach' },
  { heroId: 12, skinId: 'dozd_loki' },
  { heroId: 6, skinId: 'davood_bond' },
  { heroId: 1, skinId: 'shahin_madmax' },
  { heroId: 21, skinId: 'jasem_samjackson' },
  { heroId: 13, skinId: 'parastar_horror' },
  { heroId: 26, skinId: 'zinat_victorian' },
  { heroId: 14, skinId: 'nanjoon_christmas' },
  { heroId: 23, skinId: 'afsoon_modernfighter' },
  { heroId: 30, skinId: 'bijan_victorian' },
  { heroId: 13, skinId: 'parastar_supernurse' },
  { heroId: 9, skinId: 'ghobad_hajifirooz' },
  { heroId: 11, skinId: 'esi_rapper' },
  { heroId: 19, skinId: 'mahpeykar_wizard' },
  { heroId: 29, skinId: 'gambler_saintpatrick' },
  { heroId: 17, skinId: 'mechanic_steampunk' },
  { heroId: 28, skinId: 'pinhead_thor' },
  { heroId: 31, skinId: 'swat_robocap' },
  { heroId: 24, skinId: 'comiser_jeremybrett' },
  { heroId: 27, skinId: 'sahara_cleopatra' },
  { heroId: 8, skinId: 'doctor_adventure' },
  { heroId: 21, skinId: 'jasem_worldcup22' },
  { heroId: 32, skinId: 'chenli_whitemask' },
  { heroId: 16, skinId: 'sharare_robot' },
  { heroId: 18, skinId: 'robert_sevensin' },
  { heroId: 33, skinId: 'pirate_tropical' },
  { heroId: 7, skinId: 'sasan_saswick' },
  { heroId: 9, skinId: 'ghobad_ghobadwhite' },
  { heroId: 22, skinId: 'boxer_aztec' },
  { heroId: 23, skinId: 'afsoon_cute' },
  { heroId: 4, skinId: 'kambiz_lolo' },
  { heroId: 25, skinId: 'samurai_yakuza' },
  { heroId: 15, skinId: 'ghabrkan_nightking' },
  { heroId: 34, skinId: 'gypsy_senua' },
  { heroId: 34, skinId: 'gypsy_senua_v2' },
  { heroId: 3, skinId: 'taghi_lukyluke' },
  { heroId: 3, skinId: 'taghi_lukylukev2' },
  { heroId: 31, skinId: 'swat_blizzardfang' },
  { heroId: 10, skinId: 'heshmat_godofwar_v1' },
  { heroId: 10, skinId: 'heshmat_godofwar_v2' },
  { heroId: 36, skinId: 'babajan_diver_v1' },
  { heroId: 36, skinId: 'babajan_diver_v2' },
  { heroId: 0, skinId: 'changiz_rambov1' },
  { heroId: 0, skinId: 'changiz_rambov2' },
  { heroId: 5, skinId: 'shapoor_hawaii_v1' },
  { heroId: 5, skinId: 'shapoor_hawaii_v2' },
  { heroId: 35, skinId: 'balsamic_bababarghi_v1' },
  { heroId: 35, skinId: 'balsamic_bababarghi_v2' },
  { heroId: 20, skinId: 'zombie_ghostrider' },
  { heroId: 12, skinId: 'dozd_grunch_v1' },
  { heroId: 12, skinId: 'dozd_grunch_v2' },
  { heroId: 32, skinId: 'chenli_ling' },
  { heroId: 38, skinId: 'yavar_fisher_v1' },
  { heroId: 38, skinId: 'yavar_fisher_v2' },
  { heroId: 37, skinId: 'ammekaty_witch_v1' },
  { heroId: 37, skinId: 'ammekaty_witch_v2' },
  { heroId: 1, skinId: 'shahin_ballerina' },
  { heroId: 11, skinId: 'esi_hairdresser_v1' },
  { heroId: 11, skinId: 'esi_hairdresser_v2' },
  { heroId: 14, skinId: 'nanjoon_catwoman_v1' },
  { heroId: 14, skinId: 'nanjoon_catwoman_v2' },
  { heroId: 24, skinId: 'comiser_grims' },
  { heroId: 33, skinId: 'pirate_halloween_v1' },
  { heroId: 33, skinId: 'pirate_halloween_v2' },
  { heroId: 17, skinId: 'mechanic_madmax' },
  { heroId: 28, skinId: 'pinhead_frankenstein_v2' },
  { heroId: 28, skinId: 'pinhead_frankenstein_v1' },
];

export const SKINS_BY_HERO: Record<number, string[]> = SKINS.reduce(
  (acc, skin) => {
    const existing = acc[skin.heroId] ?? [];
    existing.push(skin.skinId);
    acc[skin.heroId] = existing;
    return acc;
  },
  {} as Record<number, string[]>
);

export const ALL_SKIN_IDS = SKINS.map((skin) => skin.skinId);
